apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "contactform.name" . }}
    chart: {{ template "contactform.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Values.mailGunApiSecret }}
type: Opaque
data:
  MmilGunApiKey: ""